#...yaml
name : CI Pipeline

on:
  push:

jobs:
  build:
    runs-on : windows-latest

    steps:
      - name : Checkout Repository
        uses : actions/checkout@v3

      - name : Set up Python
        uses : actions/setup-python@v4
        with:
          python-version: 3.11

      - name : Install Dependencies
        run: |
          pip install -r requirements.txt
      - name: run main file
        run: |
          python main.py

# only ci\cd specific code
      - name: Create CML report
        env:
          REPO_TOKEN : ${{ secrets.Personal_Token}}
        run : |
            echo "# First Line of our Report" >> report.md
            echo "## Bar Graph" >> report.md
            echo '![](./bars.png "Bar Plot")' >> report.md
            echo "## Line Plot" >> report.md
            echo '![](./lines.png "Bar Plot")' >> report.md

            cml comment create report.md

    